### PR TITLE
Add pyqi requirement under Python2

### PR DESCRIPTION
**Pull request by nsoranzo**
See https://github.com/biocore/biom-format/blob/2.1.7/setup.py#L129-L130

Also update minimum pandas version.

Add myself as maintainer.

Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by nsoranzo** [comment]
Need to move pyqi from bioconda to conda-forge: https://github.com/conda-forge/staged-recipes/pull/6940

**Comment by bgruening** [comment]
@conda-forge-admin, please rerender

**Comment by nsoranzo** [comment]
Green, thanks @bgruening !

**Comment by bgruening** [comment]
Thanks to you!

**Pull request merged**
