### PR TITLE
REL: update 2.1.8 release

### PR DESCRIPTION
**Pull request by wasade**
Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by wasade** [comment]
@conda-forge-admin, please rerender

**Comment by wasade** [comment]
In this release, we removed Python 2.7 support. It does not seem that the `azure-pipelines-*.yml` files are being updated to reflect this. The comment in those files suggests modifying `meta.yaml` should trigger an update, however I think I may be doing something incorrect here.

**Comment by nsoranzo** [comment]
@conda-forge-admin, please rerender

**Comment by nsoranzo** [comment]
@wasade The build failures are due to https://github.com/biocore/biom-format/pull/824/files#r365758675

**Comment by wasade** [comment]
Ugh, thanks. I modified `meta.yaml`. Not sure if I can retroactively fix the `pip` build, it may need to wait until 2.1.9.

**Comment by nsoranzo** [comment]
@wasade So is the plan to have biom-format depend on h5py in the future or to modify the code to keep it optional?

**Comment by wasade** [comment]
Plan is to have it depend on h5py

**Comment by nsoranzo** [comment]
> Plan is to have it depend on h5py

Cool, thanks for the clarification!

**Comment by wasade** [comment]
Travis CI builds for py3.7 and 3.8 pass within the biom-format repo -- I'm attempting to recreate the issues observed here locally.

**Comment by wasade** [comment]
I am able to recreate the issue locally, but do not understand it yet. As a result, I have deleted the release as is. It will be fixed hopefully this week, and I'll update this PR accordingly

**Comment by wasade** [comment]
@conda-forge-admin, please rerender

**Review by nsoranzo — APPROVED** [review]

**Comment by wasade** [comment]
Thanks!

**Pull request merged**
