### PR TITLE
Adding the biom-format maintainer to the feedstock

### PR DESCRIPTION
**Pull request by wasade**
Checklist
* [x] Used a fork of the feedstock to propose changes

We just released a new version of biom-format, and an auto PR was created (#1). I don't have merge permissions on this PR though. I believe this PR should allow me to have merge permissions, but I apologize if there is something amiss. For context, I am the BIOM-Format [maintainer](https://github.com/biocore/biom-format/graphs/contributors).

### CODE REVIEW

**Comment by synapticarbors** [comment]
Thanks for reaching out. I just merged #1 and will happily add you as a co-maintainer.

**Comment by wasade** [comment]
That is fantastic, thank you! And thank you for the rapid response on this!

**Comment by synapticarbors** [comment]
No problem. I get so many automated messages from conda-forge that sometimes I miss PRs that I actually need to attend to. A gentle nudge usually gets the job done. Thanks again.

**Comment by wasade** [comment]
:)

**Pull request merged**
